#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:53000/eureka/
#    instance:
#        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#        preferIpAddress: true
#feign:
#    compression:
#        request:
#            enabled: true
#            mime-types:
#            - text/xml
#            - application/xml
#            - application/json
#            min-request-size: 2048
#        response:
#            enabled: true
#    hystrix:
#        enabled: true
#logging:
#    level:
#        org:
#            springframework:
#                web: info
#        root: debug
#management:
#    endpoints:
#        web:
#            exposure:
#                include: refresh,health,info,env
server:
  port: 53020
spring:
  application:
    name: uaa
  security:
    user:
      name: root
      password: root
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-test-query: select 1
      connection-init-sql: select 1
      connection-timeout: 20000
      max-lifetime: 1200000
      auto-commit: true
      idle-timeout: 300000
    username: root
    password: 123456
    url: jdbc:mysql://internal.mysql.taoqicar.com:3306/tenancy-client?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  main:
    allow-bean-definition-overriding: true

oauth2:
  mode: auth-code
