


### {@link org.springframework.security.oauth2.provider.endpoint.TokenEndpoint}

### oauth/authorize：授权端点。
### /oauth/token：令牌端点。
### /oauth/confirm_access：用户确认授权提交端点。
### /oauth/error：授权服务错误信息端点。
### /oauth/check_token：用于资源服务访问的令牌解析端点。
### /oauth/token_key：提供公有密匙的端点，如果你使用JWT令牌的话。



### 授权码申请
POST http://127.0.0.1:53020/oauth/token?client_id=c1&client_secret=123456&grant_type=authorization_code&code=xe87T0&redirect_uri=http://www.baidu.com

### token申请
GET http://127.0.0.1:53020/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.baidu.com
