eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/

spring:
  liquibase:
    enabled: true
    change-log: classpath:config/liquibase/master.xml
    contexts: local
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://internal.mysql.taoqicar.com:3306/to-account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 128
      retryMax: 30
      scheduledDelay: 128
      scheduledThreadMax: 10
      repositorySupport: db
      #发起方为true，参与方为false
      started: false
      hmilyDbConfig:
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://internal.mysql.taoqicar.com:3306/tcc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
