server:
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 1000
      min-spare: 30
  port: 8889
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: seata-account-from

  profiles:
    active: dev

  #  配置hikari数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-test-query: select 1
      connection-init-sql: select 1
      connection-timeout: 20000
      max-lifetime: 1200000
      auto-commit: true
      idle-timeout: 300000
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
  jpa:
    #配置数据显示
    show-sql: true
    #配置mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 10.0.25.7:8848
        group: SEATA_GROUP


