spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://internal.mysql.taoqicar.com:3306/from-account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

rocketmq:
  producer:
    group: producer_bank1
  name-server: 10.0.25.169:9876