

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.91.128:3306/pay_platform_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

