server:
  port: 8808


spring:
  kafka:
    bootstrap-servers: 192.168.91.128:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: earliest
      group-id: test01

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



tenant:
  topic: c0
