server:
  port: 8889


#config security ignore urls
custom:
  security:
    ignore-urls: /**


#spring config
spring:
  profiles:
    active: @profile.active@

  application:
    name: console

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



