server:
  port: 8889


#config security ignore urls
custom:
  security:
    ignore-urls: /swagger**/**,/v1/auth/login


#spring config
spring:
  profiles:
    active: @profile.active@
  application:
    name: console
